local Clock = require(script.lib.Clock)
local Time = require(script.lib.Time)
local FromProperty = require(script.lib.FromProperty)
local FromAttribute = require(script.lib.FromAttribute)
local BindToProperty = require(script.lib.BindToProperty)
local BindToAttribute = require(script.lib.BindToAttribute)

return {
	Clock = Clock,
	Time = Time,
	FromProperty = FromProperty,
	FromAttribute = FromAttribute,
	BindToProperty = BindToProperty,
	BindToAttribute = BindToAttribute,
}
